variables:
  IMAGE_ID: '9003dd6ae819b79520afab8b9b8d26128257d740'
  # Docker Images
  DOCKER_REGISTRY: "registry.gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images"
  DOCKER_AMD64: "${DOCKER_REGISTRY}/bst16/amd64:${IMAGE_ID}"
  DOCKER_AARCH64: "${DOCKER_REGISTRY}/bst16/arm64:${IMAGE_ID}"
  DOCKER_POWERPC64LE: "${DOCKER_REGISTRY}/bst16/ppc64le:${IMAGE_ID}"

  XDG_CACHE_HOME: "${CI_PROJECT_DIR}/cache"
  # mesa-git-extension is only available through Flathub beta
  RELEASE_CHANNEL: beta 

stages:
- build
- prepare-publish
- publish
- finish-publish

before_script:
  - |
    if [ -f /cache-certificate/server.crt ]; then
    mkdir -p ~/.config
    cat >> ~/.config/buildstream.conf << EOF
    projects:
      freedesktop-sdk:
        artifacts:
          - url: https://local-cas-server:1102
            server-cert: /cache-certificate/server.crt

    EOF
    fi
  - |
    export REPO_TOKEN="${FLATHUB_REPO_TOKEN_BETA}"

.merge_request_build:
  stage: build
  interruptible: true
  except:
  - master
  - /^release\/.*/
  script:
  -  make build ARCH=${ARCH}
  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/cache/buildstream/logs

build_x86_64:
  image: $DOCKER_AMD64
  extends:
  - .merge_request_build
  variables:
    ARCH: x86_64
  tags:
    - x86_64

build_i686:
  image: $DOCKER_AMD64
  extends:
  - .merge_request_build
  variables:
    ARCH: i686
  tags:
    - x86_64

.protected_build:
  only:
  - master
  - /release\/.*/  

prepare_publish:
  extends:
  - .protected_build
  image: $DOCKER_AMD64
  stage: prepare-publish
  tags:
  - x86_64
  script:
  - flat-manager-client create https://hub.flathub.org/ "${RELEASE_CHANNEL}" > publish_build.txt
  artifacts:
    paths:
    - publish_build.txt

.publish_template: &publish
  stage: publish
  script:
  - make export-repo RELEASE_KIND=${RELEASE_CHANNEL} REPO=repo
  - flatpak build-update-repo --generate-static-deltas --prune repo
  - flat-manager-client push $(cat publish_build.txt) repo
  dependencies:
  - prepare_publish
  artifacts:
    when: always
    paths:
    - ${CI_PROJECT_DIR}/cache/buildstream/logs
  only:
  - master
  - /release\/.*/

publish_x86_64:
  image: $DOCKER_AMD64
  extends:
  - .protected_build
  - .publish_template
  tags:
  - x86_64
  - cache_x86_64
  variables:
    ARCH: x86_64

publish_i686:
  image: $DOCKER_AMD64
  extends:
  - .protected_build
  - .publish_template
  tags:
  - i686
  - cache_i686
  variables:
    ARCH: i686

finish_publish:
  image: $DOCKER_AMD64
  extends:
  - .protected_build
  stage: finish-publish
  tags:
  - x86_64
  script:
  - flat-manager-client commit --wait $(cat publish_build.txt)
  - flat-manager-client publish --wait $(cat publish_build.txt)
  - flat-manager-client purge $(cat publish_build.txt)
  dependencies:
  - prepare_publish

finish_publish_failed:
  image: $DOCKER_AMD64
  extends:
  - .protected_build
  stage: finish-publish
  tags:
  - x86_64
  script:
  - flat-manager-client purge $(cat publish_build.txt)
  when: on_failure
  dependencies:
  - prepare_publish
