variables:
  IMAGE_ID: 'latest'
  # Docker Images
  DOCKER_REGISTRY: "registry.gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images"

  XDG_CACHE_HOME: "${CI_PROJECT_DIR}/cache"
  # mesa-git-extension is only available through Flathub beta
  RELEASE_CHANNEL: beta

  BUILD_TASKS: 4
  BUILD_CPU_MULTIPLIER: 1

default:
  image: "${DOCKER_REGISTRY}/bst2:${IMAGE_ID}"
  interruptible: true
  after_script:
  - rm -rf "${XDG_CACHE_HOME}/buildstream/artifacts"
  - rm -rf "${XDG_CACHE_HOME}/buildstream/build"
  - rm -rf "${XDG_CACHE_HOME}/buildstream/cas"
  - rm -rf "${XDG_CACHE_HOME}/buildstream/sources"
  - rm -rf "${CI_PROJECT_DIR}/.bst"
  retry:
    max: 2
    when: runner_system_failure

stages:
- build
- publish
- update

workflow:
  rules:
  - if: '$CI_MERGE_REQUEST_IID'
  - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"'
  - if: '$CI_COMMIT_TAG'
  - if: '$CI_PIPELINE_SOURCE == "schedule"'

before_script:
  - |
    export REPO_TOKEN="${FLATHUB_REPO_TOKEN_BETA}"

  # Private SSL keys/certs for pushing to the CAS server
  - |
    # Force higher parallelity
    export MAX_JOBS=$(python -c "print(round(($(nproc) * ${BUILD_CPU_MULTIPLIER}) / ${BUILD_TASKS}))")
    [ -d ~/.config ] || mkdir -p ~/.config
    [ -f /cache-certificate/server.crt ] && export LOCAL_CAS=true
    python3 -mmako.cmd templates/buildstream.conf --output-file ~/.config/buildstream.conf
    cat ~/.config/buildstream.conf


.merge_request_build:
  stage: build
  except:
  - master@freedesktop-sdk/mesa-git-extension
  - /^release\/.*/@freedesktop-sdk/mesa-git-extension
  script:
  -  make build ARCH=${ARCH}
  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/cache/buildstream/logs

.builder-x86_64:
  tags:
  - x86_64
  variables:
    ARCH: x86_64
    BUILD_TASKS: 2
    BUILD_CPU_MULTIPLIER: 2

.builder-i686:
  tags:
  - x86_64
  variables:
    ARCH: i686
    BUILD_TASKS: 2
    BUILD_CPU_MULTIPLIER: 2

.builder-aarch64:
  tags:
  - aarch64
  variables:
    ARCH: aarch64

.builder-ppc64le:
  tags:
  - ppc64le
  variables:
    ARCH: ppc64le

build_x86_64:
  extends:
  - .merge_request_build
  - .builder-x86_64

build_i686:
  extends:
  - .merge_request_build
  - .builder-i686

build_aarch64:
  extends:
  - .merge_request_build
  - .builder-aarch64

build_ppc64le:
  extends:
  - .merge_request_build
  - .builder-ppc64le

.protected_build:
  only:
  - master@freedesktop-sdk/mesa-git-extension
  - /release\/.*/@freedesktop-sdk/mesa-git-extension

prepare_publish:
  extends:
  - .protected_build
  stage: publish
  script:
  - flat-manager-client create https://hub.flathub.org/ "${RELEASE_CHANNEL}" --build-log-url ${CI_PIPELINE_URL} > publish_build.txt
  except:
  - schedules
  artifacts:
    paths:
    - publish_build.txt

.publish_template:
  stage: publish
  interruptible: false
  variables:
    DISABLE_CACHE_PUSH: 1
  script:
  - make export-repo RELEASE_KIND=${RELEASE_CHANNEL} REPO=repo
  - flatpak build-update-repo repo
  - flat-manager-client push $(cat publish_build.txt) repo --build-log-url ${CI_PIPELINE_URL}
  needs:
  - prepare_publish
  artifacts:
    when: always
    paths:
    - ${CI_PROJECT_DIR}/cache/buildstream/logs
  except:
  - schedules

publish_x86_64:
  extends:
  - .protected_build
  - .publish_template
  - .builder-x86_64

publish_i686:
  extends:
  - .protected_build
  - .publish_template
  - .builder-i686

.finish_publish_base:
  extends:
  - .protected_build
  stage: publish
  needs:
  - prepare_publish
  - job: publish_x86_64
    artifacts: false
  - job: publish_i686
    artifacts: false
  except:
  - schedules

finish_publish:
  extends:
  - .finish_publish_base
  script:
  - flat-manager-client commit --wait $(cat publish_build.txt)
  - flat-manager-client publish --wait $(cat publish_build.txt)
  - flat-manager-client purge $(cat publish_build.txt)

finish_publish_failed:
  extends:
  - .finish_publish_base
  script:
  - flat-manager-client purge $(cat publish_build.txt)
  when: on_failure

track_updates:
  stage: update
  only:
  - schedules
  script:
  - git remote set-url origin "https://gitlab-ci-token:${FREEDESKTOP_API_KEY}@gitlab.com/freedesktop-sdk/mesa-git-extension.git"
  - git config user.name "freedesktop_sdk_updater"
  - git config user.email "freedesktop_sdk_updater@libreml.com"
  - git branch -f "${CI_COMMIT_REF_NAME}" "origin/${CI_COMMIT_REF_NAME}"
  - |
    case "${CI_COMMIT_REF_NAME}" in
      master)
      ;;
      release/*)
      ;;
      *)
        false
      ;;
    esac
  - GITLAB_TOKEN=$FREEDESKTOP_API_KEY auto_updater --verbose
    --base_branch "${CI_COMMIT_REF_NAME}"
    --nobuild
    --overwrite
    --push
    --create_mr
    --gitlab_project="freedesktop-sdk/mesa-git-extension"
    --max_merge_requests=4
    track-elements.bst
    freedesktop-sdk.bst

