variables:
  IMAGE_ID: '543571583e6271ede4c706aff60d389cf26a13e9'
  # Docker Images
  DOCKER_REGISTRY: "registry.gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images"

  XDG_CACHE_HOME: "${CI_PROJECT_DIR}/cache"
  BST_CACHE_SERVER_ADDRESS: 'freedesktop-sdk-cache.codethink.co.uk'
  # mesa-git-extension is only available through Flathub beta
  RELEASE_CHANNEL: beta

default:
  image: "${DOCKER_REGISTRY}/bst16:${IMAGE_ID}"

stages:
- build
- publish
- update

workflow:
  rules:
  - if: '$CI_MERGE_REQUEST_IID'
  - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"'
  - if: '$CI_COMMIT_TAG'
  - if: '$CI_PIPELINE_SOURCE == "schedule"'

before_script:
  - |
    export REPO_TOKEN="${FLATHUB_REPO_TOKEN_BETA}"

  - mkdir -p ~/.config
  - mkdir -p /etc/ssl/CAS

  # Private SSL keys/certs for pushing to the CAS server
  - |
    if [ -n "$BB_CAS_PUSH_CERT" ] && [ -n "$BB_CAS_PUSH_KEY" ]; then
      echo "$BB_CAS_PUSH_CERT" > /etc/ssl/CAS/server.crt
      echo "$BB_CAS_PUSH_KEY" > /etc/ssl/CAS/server.key
    fi

  - |
    {
      echo "projects:"
      for project in mesa-git freedesktop-sdk; do
        echo "  ${project}:"
        echo "    artifacts:"
        if [ -f /cache-certificate/server.crt ]; then
          echo "    - url: https://local-cas-server:1102"
          echo "      client-key: /etc/ssl/CAS/server.key"
          echo "      client-cert: /etc/ssl/CAS/server.crt"
          echo "      server-cert: /cache-certificate/server.crt"
          if [ "${DISABLE_CACHE_PUSH:+set}" != set ]; then
            echo "      push: true"
          fi
        fi
        if [ -n "$GITLAB_CAS_PUSH_CERT" ] && [ -n "$GITLAB_CAS_PUSH_KEY" ]; then
          echo "    - url: https://${BST_CACHE_SERVER_ADDRESS}:11002"
          echo "      client-key: /etc/ssl/CAS/server.key"
          echo "      client-cert: /etc/ssl/CAS/server.crt"
          if [ "${DISABLE_CACHE_PUSH:+set}" != set ]; then
            echo "      push: true"
          fi
        fi
      done
    } >> ~/.config/buildstream.conf

.merge_request_build:
  stage: build
  interruptible: true
  except:
  - master
  - /^release\/.*/
  script:
  -  make build ARCH=${ARCH}
  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/cache/buildstream/logs

.builder-x86_64:
  tags:
  - x86_64
  - cache_x86_64
  variables:
    ARCH: x86_64

.builder-i686:
  tags:
  - x86_64
  - cache_i686
  variables:
    ARCH: i686

build_x86_64:
  extends:
  - .merge_request_build
  - .builder-x86_64

build_i686:
  extends:
  - .merge_request_build
  - .builder-i686

.protected_build:
  only:
  - master
  - /release\/.*/ 

prepare_publish:
  extends:
  - .protected_build
  stage: publish
  script:
  - flat-manager-client create https://hub.flathub.org/ "${RELEASE_CHANNEL}" > publish_build.txt
  except:
  - schedules
  artifacts:
    paths:
    - publish_build.txt

.publish_template:
  stage: publish
  variables:
    DISABLE_CACHE_PUSH: 1
  script:
  - make export-repo RELEASE_KIND=${RELEASE_CHANNEL} REPO=repo
  - flatpak build-update-repo --generate-static-deltas --prune repo
  - flat-manager-client push $(cat publish_build.txt) repo
  needs:
  - prepare_publish
  artifacts:
    when: always
    paths:
    - ${CI_PROJECT_DIR}/cache/buildstream/logs
  only:
  - master
  - /release\/.*/
  except:
  - schedules

publish_x86_64:
  extends:
  - .protected_build
  - .publish_template
  - .builder-x86_64

publish_i686:
  extends:
  - .protected_build
  - .publish_template
  - .builder-i686

.finish_publish_base:
  extends:
  - .protected_build
  stage: publish
  needs:
  - prepare_publish
  - job: publish_x86_64
    artifacts: false
  - job: publish_i686
    artifacts: false
  except:
  - schedules

finish_publish:
  extends:
  - .finish_publish_base
  script:
  - flat-manager-client commit --wait $(cat publish_build.txt)
  - flat-manager-client publish --wait $(cat publish_build.txt)
  - flat-manager-client purge $(cat publish_build.txt)

finish_publish_failed:
  extends:
  - .finish_publish_base
  script:
  - flat-manager-client purge $(cat publish_build.txt)
  when: on_failure

track_updates:
  stage: update
  only:
  - schedules
  script:
  - git remote set-url origin "https://gitlab-ci-token:${FREEDESKTOP_API_KEY}@gitlab.com/freedesktop-sdk/mesa-git-extension.git"
  - git config user.name "freedesktop_sdk_updater"
  - git config user.email "freedesktop_sdk_updater@libreml.com"
  - git branch -f "${CI_COMMIT_REF_NAME}" "origin/${CI_COMMIT_REF_NAME}"
  - |
    case "${CI_COMMIT_REF_NAME}" in
      master)
      ;;
      release/*)
      ;;
      *)
        false
      ;;
    esac
  - GITLAB_TOKEN=$FREEDESKTOP_API_KEY auto_updater --verbose
    --base_branch "${CI_COMMIT_REF_NAME}"
    --nobuild
    --overwrite
    --push
    --create_mr
    --gitlab_project="freedesktop-sdk/mesa-git-extension"
    --max_merge_requests=4
    mesa.bst libdrm.bst freedesktop-sdk
